 version: '3.8'

 services:

   db:
       #image: mariadb
       build: ./mariadb
       restart: always
       environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: racktables
        

   nginx:
       #image: nginx
       build: ./nginx
       restart: always
       ports:
         - 4040:81

   php:
        #image: php7.4-fpm
        build: ./php
        restart: always

   php2:
        build: ./php2
        restart: always
